---
title: "The Effect of the NHSC on County-Level Mortality"
author: "Sarah Van Alsten"
output:
  pdf_document: 
    latex_engine: lualatex
    includes:  
      in_header: myheader.tex
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(rdd)
library(rdrobust)
library(kableExtra)
library(tableone)
```

```{r, echo = F, results='asis', warning = FALSE, message=FALSE}
#make a table one to show weighted scoring criteria
pcp_score <- c(0.05, .1, .15, .2, .25, .3, .35, .4, .45, .5, .55, .6, .65,
               .7, .75, .8, .85, .9, .95, 1, 1.05, 1.1, 1.15, 1.2, 1.25, 1.26)


weight_pcp <- function(x){
  if(is.na(x)){
    return(NA)
  }else if (x <= 0.05){
    return(0)
  } else if (x <= .1){
    return(0.5)
  } else if (x <= .15){
    return(1.5)
  } else if (x <= .2){
    return(2.8)
  } else if (x <= .25){
    return(4.1)
  } else if (x <= .3){
    return(5.7)
  } else if (x <= .35){
    return(7.3)
  } else if (x <= .4){
    return(9.0)
  } else if (x <= .45){
    return(10.7)
  } else if (x <= .5){
    return(12.6)
  } else if (x <= .55){
    return(14.8)
  } else if (x <= .6){
    return(16.9)
  } else if (x <= .65){
    return(19.1)
  } else if (x <= .7){
    return(20.7)
  } else if (x <= .75){
    return(21.9)
  } else if (x <= .8){
    return(23.1)
  }else if (x <= .85){
    return(24.3)
  }else if (x <= .90){
    return(25.3)
  }else if (x <= .95){
    return(25.9)
  }else if (x <= 1){
    return(26.6)
  }else if (x <= 1.05){
    return(27.2)
  }else if (x <= 1.1){
    return(27.7)
  }else if (x <= 1.15){
    return(28)
  }else if (x <= 1.2){
    return(28.3)
  }else if (x <= 1.25){
    return(28.6)
  }else {
    return(28.7)
  }
  
}

pcp_weights <- sapply(X = pcp_score, FUN = weight_pcp, simplify = "vector")
pcp_score[26] <- ">1.25"

inf_score <- c(8:37, 39, 41, 43, 45)

#classify the infant mortality
recodeInf <- function(x) {
  ifelse(is.na(x), NA,
         ifelse(x <= 8, 26,
                ifelse(x <= 9, 25.6,
                       ifelse(
                         x <= 10, 24.8,
                         ifelse(x <= 11, 24,
                                ifelse(
                                  x <= 12, 23.2,
                                  ifelse(x <= 13, 22.4,
                                         ifelse(
                                           x <= 14, 20.5,
                                           ifelse(x <= 15, 20.5,
                                                  ifelse(
                                                    x <= 16, 19.5,
                                                    ifelse(x <=
                                                             17, 18.5,
                                                           ifelse(
                                                             x <= 18, 17.5,
                                                             ifelse(x <=
                                                                      19, 16.4,
                                                                    ifelse(
                                                                      x <= 20, 15.3,
                                                                      ifelse(x <=
                                                                               21, 14.2,
                                                                             ifelse(
                                                                               x <= 22, 13.1,
                                                                               ifelse(x <=
                                                                                        23, 11.9,
                                                                                      ifelse(x <=
                                                                                               24, 10.8,
                                                                                             ifelse(
                                                                                               x <= 25, 9.6,
                                                                                               ifelse(x <=
                                                                                                        26, 8.5,
                                                                                                      ifelse(x <=
                                                                                                               27, 7.3,
                                                                                                             ifelse(
                                                                                                               x <= 28, 6.1,
                                                                                                               ifelse(x <=
                                                                                                                        29, 5.4,
                                                                                                                      ifelse(x <=
                                                                                                                               30, 5,
                                                                                                                             ifelse(
                                                                                                                               x <= 31, 4.7,
                                                                                                                               ifelse(x <=
                                                                                                                                        32, 4.3,
                                                                                                                                      ifelse(x <=
                                                                                                                                               33, 4,
                                                                                                                                             ifelse(
                                                                                                                                               x <= 34, 3.6,
                                                                                                                                               ifelse(x <=
                                                                                                                                                        35, 3.3,
                                                                                                                                                      ifelse(x <=
                                                                                                                                                               36, 3,
                                                                                                                                                             ifelse(
                                                                                                                                                               x <= 37, 2.6,
                                                                                                                                                               ifelse(x <=
                                                                                                                                                                        39, 2.0,
                                                                                                                                                                      ifelse(x <=
                                                                                                                                                                               41, 1.4,
                                                                                                                                                                             ifelse(
                                                                                                                                                                               x <= 43, 0.8,
                                                                                                                                                                               ifelse(x <= 45, 0.2, 0)
                                                                                                                                                                             )))
                                                                                                                                                             )))
                                                                                                                                             )))
                                                                                                                             )))
                                                                                                             )))
                                                                                             )))
                                                                             ))
                                                                    ))
                                                           ))
                                                  ))
                                         ))
                                ))
                       ))))
}

inf_weights <- recodeInf(inf_score)

old_score <- c(7:31)
#recode the over 65 vars
oldRecode <- function(x){
  ifelse(is.na(x), NA,
         ifelse(x<=7, 20.2,
                ifelse(x<=8, 20.1,
                       ifelse(x<=9, 19.9,
                              ifelse(x<=10, 19.8,
                                     ifelse(x<=11, 19.6,
                                            ifelse(x<=12, 19.4,
                                                   ifelse(x<=13, 19.1,
                                                          ifelse(x<=14, 18.9,
                                                                 ifelse(x<=15, 18.7,
                                                                        ifelse(x<=16, 17.8,
                                                                               ifelse(x<=17, 16.1,
                                                                                      ifelse(x<=18, 14.4,
                                                                                             ifelse(x<=19, 12.8,
                                                                                                    ifelse(x<=20, 11.2,
                                                                                                           ifelse(x<=21, 9.8,
                                                                                                                  ifelse(x<=22, 8.9,
                                                                                                                         ifelse(x<=23, 8,
                                                                                                                                ifelse(x<=24,7,
                                                                                                                                       ifelse(x<=25, 6.1,
                                                                                                                                              ifelse(x<=26, 5.1,
                                                                                                                                                     ifelse(x<=27, 4,
                                                                                                                                                            ifelse(x<=28, 2.8,
                                                                                                                                                                   ifelse(x<=29, 1.7,
                                                                                                                                                                          ifelse(x<=30, 0.6,0)))))))))))))))))))))))))
  
  
  
}

old_weights <- oldRecode(old_score)
old_score[25] <- ">30"

pov_score <- c(.1, 1, seq(4, 50, 2))
#poverty recode for IMU
povRecode <- function(x){
  return(
    ifelse(is.na(x), NA,
           ifelse(x <= .1, 25.1,
                  ifelse(x <= 1, 24.6,
                         ifelse(x <= 4, 23.7,
                                ifelse(x <= 6, 22.8,
                                       ifelse(x<=8, 21.9,
                                              ifelse(x<=10, 21,
                                                     ifelse(x<=12, 20,
                                                            ifelse(x<=14, 18.7,
                                                                   ifelse(x<=16, 17.4,
                                                                          ifelse(x<=18, 16.2,
                                                                                 ifelse(x<=20, 14.9,
                                                                                        ifelse(x<=22, 13.6,
                                                                                               ifelse(x<=24, 12.2,
                                                                                                      ifelse(x<=26, 10.9,
                                                                                                             ifelse(x<=28, 9.3,
                                                                                                                    ifelse(x<=30, 7.8,
                                                                                                                           ifelse(x<=32, 6.6,
                                                                                                                                  ifelse(x<=34, 5.6,
                                                                                                                                         ifelse(x<=36, 4.7,
                                                                                                                                                ifelse(x<=38, 3.4,
                                                                                                                                                       ifelse(x<=40, 2.1,
                                                                                                                                                              ifelse(x<=42, 1.3,
                                                                                                                                                                     ifelse(x<=44, 1,
                                                                                                                                                                            ifelse(x<=46, 0.7,
                                                                                                                                                                                   ifelse(x<=48, 0.4,
                                                                                                                                                                                          ifelse(x<=50, 0.1, 0)))))))))))))))))))))))))))
  )
}

pov_weights <- povRecode(pov_score)

tab1 <- cbind(inf_score, inf_weights, c(old_score, rep("--",9)), 
              c(old_weights, rep("--",9)),
              c(pcp_score, rep("--",8)), c(pcp_weights, rep("--",8)),
              c(pov_score, rep("--",8)), c(pov_weights, rep("--",8)))
tab1[26,7] <- "50 +"
tab1 <- as.data.frame(tab1)
names(tab1) <- c("Infant Mortality Rate", "Infant Mortality Score",
                 "Percent Population Over 65", "Over 65 Score",
                 "Primary Care to Population Ratio", "Primary Care Ratio Score",
                 "Percent Population in Poverty", "Poverty Score")

tab1[,c(1,3,5,7)] <- sapply(tab1[,c(1,3,5,7)], function(x) paste0("\u2264", x), USE.NAMES=FALSE)

tab1[,c(1,3,5,7)] <- sapply(tab1[,c(1,3,5,7)], function(x) ifelse(str_detect(x, "--"), "--",x))
tab1[,c(1,3,5,7)] <- sapply(tab1[,c(1,3,5,7)], function(x) str_replace(x, pattern ="\u2264", replacement = "<= "), USE.NAMES=FALSE)
tab1[25,3] <- ">30"
tab1[26,5] <- ">1.25"
tab1[26,7] <- ">48"
tab1[34,1] <- ">43"

tab1$`Infant Mortality Score` <- ifelse(nchar(as.character(tab1$`Infant Mortality Score`))<3,
                                        paste0(as.character(tab1$`Infant Mortality Score`), ".0"),
                                        as.character(tab1$`Infant Mortality Score`))

tab1$`Over 65 Score` <- ifelse(nchar(as.character(tab1$`Over 65 Score`))<3 &
                                 !str_detect(as.character(tab1$`Over 65 Score`), "--"),
                                        paste0(as.character(tab1$`Over 65 Score`), ".0"),
                                        as.character(tab1$`Over 65 Score`))

tab1$`Primary Care Ratio Score` <- ifelse(nchar(as.character(tab1$`Primary Care Ratio Score`))<3 &
                                 !str_detect(as.character(tab1$`Primary Care Ratio Score`), "--"),
                               paste0(as.character(tab1$`Primary Care Ratio Score`), ".0"),
                               as.character(tab1$`Primary Care Ratio Score`))

tab1$`Poverty Score` <- ifelse(nchar(as.character(tab1$`Poverty Score`))<3 &
                                 !str_detect(as.character(tab1$`Poverty Score`), "--"),
                               paste0(as.character(tab1$`Poverty Score`), ".0"),
                               as.character(tab1$`Poverty Score`))




names(tab1) <- c(rep(c("Value", "Score"),4))
tab1 %>% kableExtra::kable("latex",booktabs = T, escape = TRUE, align = "r",
                           caption = "Description of index of medical underservice score subcomponents and weighting") %>%
  # here you can add the vertical line, in my example, for all the columns
  kableExtra::column_spec (1:7) %>%
  kableExtra::kable_styling("latex")%>%
  add_header_above(c("Infant Mortality" = 2, "Percent  Over 65" = 2,
                     "Primary Care Ratio" = 2, "Percent  in Poverty" = 2))%>%
  footnote(number = c("Infant Mortality Rate = Infant Deaths per 1000 Live Births",
                      "PCP Ratio = Total FTE Non-federal Primary Care Providers per 1000 Population",
                      "Poverty = At or Below Federal Poverty Level"))
  
```


```{r}

merge.mortb <- read_csv("C:\\Users\\Owner\\OneDrive\\Documents\\Spring2020\\imu_data\\data\\final_IMU_analysis_data.csv")
merge.mortb <- janitor::clean_names(merge.mortb)
merge.mortb <- merge.mortb[!(merge.mortb$treatment == 1 & merge.mortb$newimu14 > 62),]


col1 <- c("620", "290 (47.90)", "0.17 (0.03)", "0.13 (0.05)", "25.67 (1.70)", "0.81 (0.57)",
          "29,304 (55,339)","0.75 (0.24)","0.76 (0.20)","0.12 (0.17)","0.08 (0.14)",
          "0.24 (0.06)","0.33 (0.04)","0.30 (0.05)","0.16 (0.04)")
col2 <- c("690","0 (0.00)","0.14 (0.05)","0.14 (0.05)","24.76 (0.74)","1.36 (0.60)",
        "54,822 (129,421)","0.60 (0.26)","0.81 (0.18)","0.07 (0.11)",
          "0.09 (0.14)","0.22 (0.06)","0.32 (0.04)","0.26 (0.04)","0.14 (0.04)")
col3 <- c("--", "--", rep( "< 0.001",8), "0.001", rep("< 0.001",4))

tab2 <- cbind.data.frame(col1, col2, col3)
names(tab2) <- c("IMU > 51.88 and <= 62",	"IMU > 62 and <= 72.11",	"P-value")
rownames(tab2) <- c("N", "Enrolled in NHSC",  "Poverty\\textsuperscript{1}","Older Than 65 Years", "Infant Health Index\\textsuperscript{2}",  "Primary Care Ratio\\textsuperscript{3}",	 "Total Population" ,"Rural", "Non-Hispanic White",	"Non-Hispanic Black",   "Hispanic",	"Current Smokers"	, "Obese"	, "Physically Inactive" ,"Uninsured")

tab2 %>%
  kable("latex", align =c("c", "c", "r"), 
        booktabs = TRUE, caption = "Sample characteristics of counties with Index of Medical Underservice (IMU) scores within the median IK bandwidth. All characteristics are based on 2014 data or, for IMU components, the five-year average of 2009-2014 data and are shown as Mean (SD). Except for total population, infant health index, and primary care ratio, all values represent proportions of county residents with given characteristic.", escape = FALSE) %>%
  group_rows(start_row = 1, end_row = 2) %>%
  group_rows(start_row = 3, end_row = 6, group_label = "IMU Components") %>%
  group_rows(start_row = 7, end_row = 11, group_label = "County Characteristics") %>%
  group_rows(start_row = 12, end_row = 15, group_label = "Health Indicators")%>%
  footnote(number = c("Poverty = At or Below Federal Poverty Level",
  "Infant Mortality Rate = Infant Deaths per 1000 Live Births",
                      "PCP Ratio = Total FTE Non-federal Primary Care Providers per 1000 Population"
                      ))


```




```{r, results = 'asis', echo = FALSE, message = FALSE, warning = FALSE}
#Write a function that will make a plot of the RDD using various bandwidths
#(including the IK bandwidth)
#also see flexibility of model specification usign iv approach given this is a fuzzy rd

set.seed(48104)
# RD Effect for main outcome variable  ==> Local linear polynomial estimation with optimal bandwidth
ac.a.1 <- rdrobust(merge.mortb$age_adjusted_rate_2015a, 
                merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                c = 62, all=TRUE,masspoints = F)
ac.a.2 <- rdrobust(merge.mortb$age_adjusted_rate_2015a, 
                   merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                   c = 62, all=TRUE, p = 2,masspoints = F)
ac.a.3 <- rdrobust(merge.mortb$age_adjusted_rate_2015a, 
                   merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                   c = 62, all=TRUE, p = 3,masspoints = F)
hd.a.1 <- rdrobust(merge.mortb$age_adjusted_rate_2015h, 
                   merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                   c = 62, all=TRUE,masspoints = F)
hd.a.2 <- rdrobust(merge.mortb$age_adjusted_rate_2015h, 
                   merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                   c = 62, all=TRUE, p = 2,masspoints = F)
hd.a.3 <- rdrobust(merge.mortb$age_adjusted_rate_2015h, 
                   merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                   c = 62, all=TRUE, p = 3,masspoints = F)
ca.a.1 <- rdrobust(merge.mortb$age_adjusted_rate_2015c, 
                   merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                   c = 62, all=TRUE,masspoints = F)
ca.a.2 <- rdrobust(merge.mortb$age_adjusted_rate_2015c, 
                   merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                   c = 62, all=TRUE, p = 2,masspoints = F)
ca.a.3 <- rdrobust(merge.mortb$age_adjusted_rate_2015c, 
                   merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                   c = 62, all=TRUE, p = 3,masspoints = F)

ac.c.1 <- rdrobust(merge.mortb$crude_rate_2015a, 
                   merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                   c = 62, all=TRUE,masspoints = F)
ac.c.2 <- rdrobust(merge.mortb$crude_rate_2015a, 
                   merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                   c = 62, all=TRUE, p = 2,masspoints = F)
ac.c.3 <- rdrobust(merge.mortb$crude_rate_2015a, 
                   merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                   c = 62, all=TRUE, p = 3,masspoints = F)
hd.c.1 <- rdrobust(merge.mortb$crude_rate_2015h, 
                   merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                   c = 62, all=TRUE,masspoints = F)
hd.c.2 <- rdrobust(merge.mortb$crude_rate_2015h, 
                   merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                   c = 62, all=TRUE, p = 2,masspoints = F)
hd.c.3 <- rdrobust(merge.mortb$crude_rate_2015h, 
                   merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                   c = 62, all=TRUE, p = 3,masspoints = F)
ca.c.1 <- rdrobust(merge.mortb$crude_rate_2015c, 
                   merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                   c = 62, all=TRUE,masspoints = F)
ca.c.2 <- rdrobust(merge.mortb$crude_rate_2015c, 
                   merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                   c = 62, all=TRUE, p = 2,masspoints = F)
ca.c.3 <- rdrobust(merge.mortb$crude_rate_2015c, 
                   merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                   c = 62, all=TRUE, p = 3,masspoints = F)


#create a nice table of results
outcome <- c(rep(c(rep("All Cause",3), rep("Heart Disease", 3), rep("Cancer", 3)), 2))

polys <- c(rep(1:3,6))

bandwidths <- c(ac.a.1$bws[1,1], ac.a.2$bws[1,1], ac.a.3$bws[1,1],
                hd.a.1$bws[1,1], hd.a.2$bws[1,1], hd.a.3$bws[1,1],
                ca.a.1$bws[1,1], ca.a.2$bws[1,1], ca.a.3$bws[1,1],
                ac.c.1$bws[1,1], ac.c.2$bws[1,1], ac.c.3$bws[1,1],
                hd.c.1$bws[1,1], hd.c.2$bws[1,1], hd.c.3$bws[1,1],
                ca.c.1$bws[1,1], ca.c.2$bws[1,1], ca.c.3$bws[1,1])

tau.rdd <- c(ac.a.1$Estimate[2], ac.a.2$Estimate[2], ac.a.3$Estimate[2],
             hd.a.1$Estimate[2], hd.a.2$Estimate[2], hd.a.3$Estimate[2],
             ca.a.1$Estimate[2], ca.a.2$Estimate[2], ca.a.3$Estimate[2],
             ac.c.1$Estimate[2], ac.c.2$Estimate[2], ac.c.3$Estimate[2],
             hd.c.1$Estimate[2], hd.c.2$Estimate[2], hd.c.3$Estimate[2],
             ca.c.1$Estimate[2], ca.c.2$Estimate[2], ca.c.3$Estimate[2])

ci.conv <- c(paste0(round(ac.a.1$Estimate[2]- 1.96*ac.a.1$se[1],2), " - ", round(ac.a.1$Estimate[2]+ 1.96*ac.a.1$se[1],2)),
             paste0(round(ac.a.2$Estimate[2]- 1.96*ac.a.2$se[1],2), " - ", round(ac.a.2$Estimate[2]+ 1.96*ac.a.2$se[1],2)),
             paste0(round(ac.a.3$Estimate[2]- 1.96*ac.a.1$se[1],2), " - ", round(ac.a.3$Estimate[2]+ 1.96*ac.a.1$se[1],2)),
             paste0(round(hd.a.1$Estimate[2]- 1.96*hd.a.1$se[1],2), " - ", round(hd.a.1$Estimate[2]+ 1.96*hd.a.1$se[1],2)),
             paste0(round(hd.a.2$Estimate[2]- 1.96*hd.a.2$se[1],2), " - ", round(hd.a.2$Estimate[2]+ 1.96*hd.a.2$se[1],2)),
             paste0(round(hd.a.3$Estimate[2]- 1.96*hd.a.1$se[1],2), " - ", round(hd.a.3$Estimate[2]+ 1.96*hd.a.1$se[1],2)),
             paste0(round(ca.a.1$Estimate[2]- 1.96*ca.a.1$se[1],2), " - ", round(ca.a.1$Estimate[2]+ 1.96*ca.a.1$se[1],2)),
             paste0(round(ca.a.2$Estimate[2]- 1.96*ca.a.2$se[1],2), " - ", round(ca.a.2$Estimate[2]+ 1.96*ca.a.2$se[1],2)),
             paste0(round(ca.a.3$Estimate[2]- 1.96*ca.a.1$se[1],2), " - ", round(ca.a.3$Estimate[2]+ 1.96*ca.a.1$se[1],2)),
             paste0(round(ac.c.1$Estimate[2]- 1.96*ac.c.1$se[1],2), " - ", round(ac.c.1$Estimate[2]+ 1.96*ac.c.1$se[1],2)),
             paste0(round(ac.c.2$Estimate[2]- 1.96*ac.c.2$se[1],2), " - ", round(ac.c.2$Estimate[2]+ 1.96*ac.c.2$se[1],2)),
             paste0(round(ac.c.3$Estimate[2]- 1.96*ac.c.1$se[1],2), " - ", round(ac.c.3$Estimate[2]+ 1.96*ac.c.1$se[1],2)),
             paste0(round(hd.c.1$Estimate[2]- 1.96*hd.c.1$se[1],2), " - ", round(hd.c.1$Estimate[2]+ 1.96*hd.c.1$se[1],2)),
             paste0(round(hd.c.2$Estimate[2]- 1.96*hd.c.2$se[1],2), " - ", round(hd.c.2$Estimate[2]+ 1.96*hd.c.2$se[1],2)),
             paste0(round(hd.c.3$Estimate[2]- 1.96*hd.c.1$se[1],2), " - ", round(hd.c.3$Estimate[2]+ 1.96*hd.c.1$se[1],2)),
             paste0(round(ca.c.1$Estimate[2]- 1.96*ca.c.1$se[1],2), " - ", round(ca.c.1$Estimate[2]+ 1.96*ca.c.1$se[1],2)),
             paste0(round(ca.c.2$Estimate[2]- 1.96*ca.c.2$se[1],2), " - ", round(ca.c.2$Estimate[2]+ 1.96*ca.c.2$se[1],2)),
             paste0(round(ca.c.3$Estimate[2]- 1.96*ca.c.1$se[1],2), " - ", round(ca.c.3$Estimate[2]+ 1.96*ca.c.1$se[1],2)))


ci.robu <- c(paste0(round(ac.a.1$Estimate[2]- 1.96*ac.a.1$se[3],2), " - ", round(ac.a.1$Estimate[2]+ 1.96*ac.a.1$se[3],2)),
             paste0(round(ac.a.2$Estimate[2]- 1.96*ac.a.2$se[3],2), " - ", round(ac.a.2$Estimate[2]+ 1.96*ac.a.2$se[3],2)),
             paste0(round(ac.a.3$Estimate[2]- 1.96*ac.a.1$se[3],2), " - ", round(ac.a.3$Estimate[2]+ 1.96*ac.a.1$se[3],2)),
             paste0(round(hd.a.1$Estimate[2]- 1.96*hd.a.1$se[3],2), " - ", round(hd.a.1$Estimate[2]+ 1.96*hd.a.1$se[3],2)),
             paste0(round(hd.a.2$Estimate[2]- 1.96*hd.a.2$se[3],2), " - ", round(hd.a.2$Estimate[2]+ 1.96*hd.a.2$se[3],2)),
             paste0(round(hd.a.3$Estimate[2]- 1.96*hd.a.1$se[3],2), " - ", round(hd.a.3$Estimate[2]+ 1.96*hd.a.1$se[3],2)),
             paste0(round(ca.a.1$Estimate[2]- 1.96*ca.a.1$se[3],2), " - ", round(ca.a.1$Estimate[2]+ 1.96*ca.a.1$se[3],2)),
             paste0(round(ca.a.2$Estimate[2]- 1.96*ca.a.2$se[3],2), " - ", round(ca.a.2$Estimate[2]+ 1.96*ca.a.2$se[3],2)),
             paste0(round(ca.a.3$Estimate[2]- 1.96*ca.a.1$se[3],2), " - ", round(ca.a.3$Estimate[2]+ 1.96*ca.a.1$se[3],2)),
             paste0(round(ac.c.1$Estimate[2]- 1.96*ac.c.1$se[3],2), " - ", round(ac.c.1$Estimate[2]+ 1.96*ac.c.1$se[3],2)),
             paste0(round(ac.c.2$Estimate[2]- 1.96*ac.c.2$se[3],2), " - ", round(ac.c.2$Estimate[2]+ 1.96*ac.c.2$se[3],2)),
             paste0(round(ac.c.3$Estimate[2]- 1.96*ac.c.1$se[3],2), " - ", round(ac.c.3$Estimate[2]+ 1.96*ac.c.1$se[3],2)),
             paste0(round(hd.c.1$Estimate[2]- 1.96*hd.c.1$se[3],2), " - ", round(hd.c.1$Estimate[2]+ 1.96*hd.c.1$se[3],2)),
             paste0(round(hd.c.2$Estimate[2]- 1.96*hd.c.2$se[3],2), " - ", round(hd.c.2$Estimate[2]+ 1.96*hd.c.2$se[3],2)),
             paste0(round(hd.c.3$Estimate[2]- 1.96*hd.c.1$se[3],2), " - ", round(hd.c.3$Estimate[2]+ 1.96*hd.c.1$se[3],2)),
             paste0(round(ca.c.1$Estimate[2]- 1.96*ca.c.1$se[3],2), " - ", round(ca.c.1$Estimate[2]+ 1.96*ca.c.1$se[3],2)),
             paste0(round(ca.c.2$Estimate[2]- 1.96*ca.c.2$se[3],2), " - ", round(ca.c.2$Estimate[2]+ 1.96*ca.c.2$se[3],2)),
             paste0(round(ca.c.3$Estimate[2]- 1.96*ca.c.1$se[3],2), " - ", round(ca.c.3$Estimate[2]+ 1.96*ca.c.1$se[3],2)))

#bind together for table
res.tab <- cbind.data.frame(outcome, polys, bandwidths, tau.rdd, ci.conv, ci.robu)
res.tab$bandwidths <- round(res.tab$bandwidths, 2)
res.tab$tau.rdd <- round(res.tab$tau.rdd, 2)

names(res.tab) <- c("Outcome", "Order", "BW", "Estimate", "Conventional", "Robust")

res.tab %>%
  #this will get labelled later
  mutate(Outcome = rep(c("All Cause", " ", " ",
                     "Heart Disease", " ", " ",
                     "Cancer", " ", " "),2)) %>%
  #specify which ones should be bold
  mutate(
     Conventional = cell_spec(Conventional, 
                              bold = ifelse(substr(Conventional,1,1)!= "-", T, F)),
     Robust = cell_spec(Robust, bold = ifelse(substr(Robust,1,1)!= "-", T, F))) %>%
  kable("latex", booktabs = T, escape = F, align= c('l', 'r', 'r', 'r', 'r', 'r'),
        caption = "Effect of NHSC Participation on County-Level Mortality") %>%
  kable_styling(row_label_position = "l",) %>%
  add_header_above(c(" ", " ", " ", " ", "95% Confidence Interval" = 2)) %>%
  group_rows(start_row = 1, end_row= 9, group_label = "Age Adjusted Rate") %>%
  group_rows(start_row = 10, end_row = 18, group_label = "Crude Rate") %>%
  footnote(general = "Estimates represent tau FRD using a local regression with a triangular kernel")%>%
  add_footnote(label = "Bold face denotes statistical significance (p < 0.05)")

```

```{r, fig.cap='McCrary Density Test shows no evidence of sorting at the cutoff (p = 0.68)', results='hide', fig.pos = 'h'}
`IMU Score 2014`<- merge.mortb$imu14
rddapp::dc_test(`IMU Score 2014`, 62, bw = 10.11)

```

```{r}
#figure showing sensitivity to bw choice

make_rdd_plot_data <- function(outcome, cut = merge.mortb$newimu14, covars = NULL){
  ik.bw <- IKbandwidth(Y = outcome,
                       X = cut, cutpoint = 62)

  tempframe <- cbind.data.frame(c(1:24, ik.bw),
                                rep(0,25),
                                rep(0,25),
                                rep(0,25),
                                rep(0,25),
                                rep(0,25),
                                rep(0,25),
                                rep(0,25))

  names(tempframe) <- c("bw", "estimate_bc", "estimate_us", "upper_bc","lower_bc",
                         "upper_rob","lower_rob",
                         "nObs")

  for (i in 1:nrow(tempframe)){
    j <- tempframe[i,1]
      rd <- rdrobust(y = outcome, 
                x = cut, fuzzy = merge.mortb$treatment, h = j,
                c = 62, all=TRUE , masspoints = F, p = 2)
     tempframe[i,] <- c(j,
                       rd$Estimate[2],
                       rd$Estimate[2],
                       rd$ci[2,2], rd$ci[2,1],
                       rd$ci[3,2], rd$ci[3,1],
                       sum(rd$N_h))
  }
  
  
  return(tempframe)  
}

plot_rdd_data <- function(dat){
  int <- dat[25,1] #ik bw
  dat <- dat %>% filter(bw >= 2)
  ymin <- min(dat$lower_rob)
  ymax <- max(dat$upper_rob)
  dat %>%
    ggplot(aes(x = bw, y = estimate_bc)) + geom_point(color = "black") +
    geom_ribbon(aes(ymin = lower_rob, ymax = upper_rob), alpha =.3, fill = "#00BFC4") +
    geom_point(aes(x = bw, y = estimate_us), color = "#F8766D") + 
    geom_ribbon(aes(ymin = lower_bc, ymax = upper_bc), alpha =.3, fill = "#F8766D") +
    theme_bw() + labs(x = "Absolute Distance From Cutoff", y = "LATE")+
    geom_text(aes(label = paste(nObs)), nudge_y = 250, nudge_x = -.2,
              check_overlap = TRUE, angle = 60)+
    geom_vline(xintercept = int, linetype = "dashed", color = "darkgrey")+
    geom_hline(yintercept = 0, color = "black")+
    xlim(c(2,23))+ theme(panel.grid.minor.x = element_blank()) +
    ylim(c(ymin + 50 , ymax - 50))

}

plot_rdd_data2 <- function(dat){
  int <- dat[25,1] #ik bw
  dat <- dat %>% filter(bw >= 2)
  ymin <- min(dat$lower_rob)
  ymax <- max(dat$upper_rob)
  dat %>%
    ggplot(aes(x = bw, y = estimate_bc)) + geom_point(color = "black") +
    geom_ribbon(aes(ymin = lower_rob, ymax = upper_rob), alpha =.3, fill = "#00BFC4") +
    geom_point(aes(x = bw, y = estimate_us), color = "#F8766D") + 
    geom_ribbon(aes(ymin = lower_bc, ymax = upper_bc), alpha =.3, fill = "#F8766D") +
    theme_bw() + labs(x = "Absolute Distance From Cutoff", y = "LATE")+
    geom_text(aes(label = paste(nObs)), nudge_y = 50, nudge_x = -.2,
              check_overlap = TRUE, angle = 60)+
    geom_vline(xintercept = int, linetype = "dashed", color = "darkgrey")+
    geom_hline(yintercept = 0, color = "black")+
    xlim(c(2,23))+ theme(panel.grid.minor.x = element_blank()) +
    ylim(c(ymin + 50 , ymax - 50))

}

all.cause.age <- 
  make_rdd_plot_data(merge.mortb$age_adjusted_rate_2015a) %>%
  plot_rdd_data()

all.cause.crude <- 
  make_rdd_plot_data(merge.mortb$crude_rate_2015a) %>%
  plot_rdd_data()

heart.age <- 
  make_rdd_plot_data(merge.mortb$age_adjusted_rate_2015h) %>%
  plot_rdd_data()

heart.crude <- 
  make_rdd_plot_data(merge.mortb$crude_rate_2015h) %>%
  plot_rdd_data()

cancer.age <- 
  make_rdd_plot_data(merge.mortb$age_adjusted_rate_2015c) %>%
  plot_rdd_data2()

cancer.crude <- 
  make_rdd_plot_data(merge.mortb$crude_rate_2015c) %>%
  plot_rdd_data2()

```


```{r,fig.cap="Age-standardized (top) LATE estimates for all-cause mortality are robust against choice of bandwidht, while crude (bottom) effect estimates are not. LATE is estimated as a local fuzzy RDD with a triangular kernel and second-order polynomial. Dashed line indicates IK bandwidth, numbers reflect number of observations within a given bandwidth, blue ribbon represents robust 95% CI, and dark ribbon represents bias-corrected 95% CI", fig.height=10, fig.width=8}
library(patchwork)
all.cause.age / all.cause.crude + plot_annotation(title = "Effect of NHSC on All-Cause Mortality Rate")

```


```{r,fig.cap="Age-standardized (top) and crude (bottom) effect estimates for heart disease mortality are robust against choice of bandwidth. LATE is estimated as a local fuzzy RDD with a triangular kernel and second-order polynomial. Dashed line indicates IK bandwidth, numbers reflect number of observations within a given bandwidth, blue ribbon represents robust 95% CI, and dark ribbon represents bias-corrected 95% CI", fig.height=10, fig.width=8}
heart.age / heart.crude+ plot_annotation(title = "Effect of NHSC on Heart Disease Mortality Rate")

```


```{r,fig.cap="Age-standardized (top) and crude (bottom) effect estimates for cancer mortality are robust against choice of bandwidth. LATE is estimated as a local fuzzy RDD with a triangular kernel and second-order polynomial. Dashed line indicates IK bandwidth, numbers reflect number of observations within a given bandwidth, blue ribbon represents robust 95% CI, and dark ribbon represents bias-corrected 95% CI", fig.height=10, fig.width=8}
cancer.age / cancer.crude+ plot_annotation(title = "Effect of NHSC on Cancer Mortality Rate")

```




## Supplementary Material and Sensitivity Analyses


### FRDD Specifications
```{r}
#figure showing how models look with different polynomial specifications
########################################################
#make plots to pick ones to use
a1<-
rdrobust::rdplot(merge.mortb$age_adjusted_rate_2015a, 
                 merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                 c = 62, all=TRUE, p = 1, title = "Age Adjusted All-Cause: Linear",
                 x.label = "2014 IMU Score", y.label = "Age Adjusted Rate", ci = 95, hide = T)
a2<-
rdrobust::rdplot(merge.mortb$age_adjusted_rate_2015a, 
                 merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                 c = 62, all=TRUE, p = 2, title = "Age Adjusted All-Cause: Quadratic",
                 x.label = "2014 IMU Score", y.label = "Age Adjusted Rate", ci = 95, hide = T)
a3<-
rdrobust::rdplot(merge.mortb$age_adjusted_rate_2015a, 
                 merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                 c = 62, all=TRUE, p = 3,title = "Age Adjusted All-Cause: Cubic",
                 x.label = "2014 IMU Score", y.label = "Age Adjusted Rate", ci = 95, hide = T)

h1<-
rdrobust::rdplot(merge.mortb$age_adjusted_rate_2015h, 
                 merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                 c = 62, all=TRUE, p = 1, title = "Age Adjusted Heart Disease: Linear",
                 x.label = "2014 IMU Score", y.label = "Age Adjusted Rate", ci = 95, hide = T)
h2<-
rdrobust::rdplot(merge.mortb$age_adjusted_rate_2015h, 
                 merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                 c = 62, all=TRUE, p = 2, title = "Age Adjusted Heart Disease: Quadratic",
                 x.label = "2014 IMU Score", y.label = "Age Adjusted Rate", ci = 95, hide = T)
h3<-
rdrobust::rdplot(merge.mortb$age_adjusted_rate_2015h, 
                 merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                 c = 62, all=TRUE, p = 3,title = "Age Adjusted Heart Disease: Cubic",
                 x.label = "2014 IMU Score", y.label = "Age Adjusted Rate", ci = 95, hide = T)

c1<- 
rdrobust::rdplot(merge.mortb$age_adjusted_rate_2015c, 
                 merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                 c = 62, all=TRUE, p = 1, title = "Age Adjusted Cancer: Linear",
                 x.label = "2014 IMU Score", y.label = "Age Adjusted Rate", ci = 95, hide = T)
c2<-
rdrobust::rdplot(merge.mortb$age_adjusted_rate_2015c, 
                 merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                 c = 62, all=TRUE, p = 2, title = "Age Adjusted Heart Cancer: Quadratic",
                 x.label = "2014 IMU Score", y.label = "Age Adjusted Rate", ci = 95, hide = T)
c3<-
rdrobust::rdplot(merge.mortb$age_adjusted_rate_2015c, 
                 merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                 c = 62, all=TRUE, p = 3,title = "Age Adjusted Heart Cancer: Cubic",
                 x.label = "2014 IMU Score", y.label = "Age Adjusted Rate", ci = 95, hide = T)

a4<-
rdrobust::rdplot(merge.mortb$crude_rate_2015a, 
                 merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                 c = 62, all=TRUE, p = 1, title = "Crude All-Cause: Linear",
                 x.label = "2014 IMU Score", y.label = "Crude Rate", ci = 95, hide = T)
a5<-
rdrobust::rdplot(merge.mortb$crude_rate_2015a, 
                 merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                 c = 62, all=TRUE, p = 2, title = "Crude All-Cause: Quadratic",
                 x.label = "2014 IMU Score", y.label = "Crude Rate", ci = 95, hide = T)
a6<-
rdrobust::rdplot(merge.mortb$crude_rate_2015a, 
                 merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                 c = 62, all=TRUE, p = 3,title = "Crude All-Cause: Cubic",
                 x.label = "2014 IMU Score", y.label = "Crude Rate", ci = 95, hide = T)

h4<-
rdrobust::rdplot(merge.mortb$crude_rate_2015h, 
                 merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                 c = 62, all=TRUE, p = 1, title = "Crude Heart Disease: Linear",
                 x.label = "2014 IMU Score", y.label = "Crude Rate", ci = 95, hide = T)
h5<-
rdrobust::rdplot(merge.mortb$crude_rate_2015h, 
                 merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                 c = 62, all=TRUE, p = 2, title = "Crude Heart Disease: Quadratic",
                 x.label = "2014 IMU Score", y.label = "Crude Rate", ci = 95, hide = T)
h6<-
rdrobust::rdplot(merge.mortb$crude_rate_2015h, 
                 merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                 c = 62, all=TRUE, p = 3,title = "Crude Heart Disease: Cubic",
                 x.label = "2014 IMU Score", y.label = "Crude Rate", ci = 95, hide = T)
c4<-
rdrobust::rdplot(merge.mortb$crude_rate_2015c, 
                 merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                 c = 62, all=TRUE, p = 1, title = "Crude Cancer: Linear",
                 x.label = "2014 IMU Score", y.label = "Crude Rate", ci = 95, hide = T)
c5<-
rdrobust::rdplot(merge.mortb$crude_rate_2015c, 
                 merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                 c = 62, all=TRUE, p = 2, title = "Crude Heart Cancer: Quadratic",
                 x.label = "2014 IMU Score", y.label = "Crude Rate", ci = 95, hide = T)
c6<-
rdrobust::rdplot(merge.mortb$crude_rate_2015c, 
                 merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
                 c = 62, all=TRUE, p = 3,title = "Crude Heart Cancer: Cubic",
                 x.label = "2014 IMU Score", y.label = "Crude Rate", ci = 95, hide = T)
```


```{r}

ac1 <- 
a1$vars_bins %>%
  mutate(predicted_y = ifelse(rdplot_mean_bin <= 62,
                              a1$coef[2,1]*-1*rdplot_mean_bin+a1$coef[1,2],
                              a1$coef[2,2]*rdplot_mean_bin +a1$coef[1,1])) %>%
  filter(!is.nan(rdplot_ci_r) & !is.nan(rdplot_mean_y) & !is.na(rdplot_ci_r) &
           rdplot_N != 1) %>%
  ggplot(aes(x = rdplot_mean_bin, y = rdplot_mean_y)) + 
  geom_point() +
  geom_ribbon(aes(ymin = rdplot_ci_l, ymax = rdplot_ci_r), alpha = .1) + theme_bw() +
  geom_vline(xintercept = 62, linetype = "dashed", color = "darkgrey") +
  geom_line(color= ifelse(a1$vars_poly$rdplot_x <= 62, "red", "blue"),
            aes(x=rdplot_x, y= rdplot_y), data = a1$vars_poly) +
  labs(x = "2014 Index of Medical Score", y = "Mortality Rate") +
  ggtitle("Linear")

ac2 <- 
a2$vars_bins %>%
  mutate(predicted_y = ifelse(rdplot_mean_bin <= 62,
                              a2$coef[2,1]*-1*rdplot_mean_bin+a2$coef[1,2],
                              a2$coef[2,2]*rdplot_mean_bin +a2$coef[1,1])) %>%
  filter(!is.nan(rdplot_ci_r) & !is.nan(rdplot_mean_y) & !is.na(rdplot_ci_r) &
           rdplot_N != 1) %>%
  ggplot(aes(x = rdplot_mean_bin, y = rdplot_mean_y)) + 
  geom_point() +
  geom_ribbon(aes(ymin = rdplot_ci_l, ymax = rdplot_ci_r), alpha = .1) + theme_bw() +
  geom_vline(xintercept = 62, linetype = "dashed", color = "darkgrey") +
  geom_line(color= ifelse(a2$vars_poly$rdplot_x <= 62, "red", "blue"),
            aes(x=rdplot_x, y= rdplot_y), data = a2$vars_poly) +
  labs(x = "2014 Index of Medical Score", y = "Mortality Rate") +
  ggtitle("Quadratic")

ac3 <- 
a3$vars_bins %>%
  filter(!is.nan(rdplot_ci_r) & !is.nan(rdplot_mean_y) & !is.na(rdplot_ci_r) &
           rdplot_N != 1) %>%
  ggplot(aes(x = rdplot_mean_bin, y = rdplot_mean_y)) + 
  geom_point() +
  geom_ribbon(aes(ymin = rdplot_ci_l, ymax = rdplot_ci_r), alpha = .1) + theme_bw() +
  geom_vline(xintercept = 62, linetype = "dashed", color = "darkgrey") +
  geom_line(color= ifelse(a3$vars_poly$rdplot_x <= 62, "red", "blue"),
            aes(x=rdplot_x, y= rdplot_y), data = a3$vars_poly) +
  labs(x = "2014 Index of Medical Score", y = "Mortality Rate") +
  ggtitle("Cubic")

hd1 <- 
h1$vars_bins %>%
  filter(!is.nan(rdplot_ci_r) & !is.nan(rdplot_mean_y) & !is.na(rdplot_ci_r) &
           rdplot_N != 1) %>%
  ggplot(aes(x = rdplot_mean_bin, y = rdplot_mean_y)) + 
  geom_point() +
  geom_ribbon(aes(ymin = rdplot_ci_l, ymax = rdplot_ci_r), alpha = .1) + theme_bw() +
  geom_vline(xintercept = 62, linetype = "dashed", color = "darkgrey") +
  geom_line(color= ifelse(h1$vars_poly$rdplot_x <= 62, "red", "blue"),
            aes(x=rdplot_x, y= rdplot_y), data = h1$vars_poly) +
  labs(x = "2014 Index of Medical Score", y = "Mortality Rate") +
  ggtitle("Linear")

hd2 <- 
h2$vars_bins %>%
  mutate(predicted_y = ifelse(rdplot_mean_bin <= 62,
                              h2$coef[2,1]*-1*rdplot_mean_bin+h2$coef[1,2],
                              h2$coef[2,2]*rdplot_mean_bin +h2$coef[1,1])) %>%
  filter(!is.nan(rdplot_ci_r) & !is.nan(rdplot_mean_y) & !is.na(rdplot_ci_r) &
           rdplot_N != 1) %>%
  ggplot(aes(x = rdplot_mean_bin, y = rdplot_mean_y)) + 
  geom_point() +
  geom_ribbon(aes(ymin = rdplot_ci_l, ymax = rdplot_ci_r), alpha = .1) + theme_bw() +
  geom_vline(xintercept = 62, linetype = "dashed", color = "darkgrey") +
  geom_line(color= ifelse(h2$vars_poly$rdplot_x <= 62, "red", "blue"),
            aes(x=rdplot_x, y= rdplot_y), data = h2$vars_poly) +
  labs(x = "2014 Index of Medical Score", y = "Mortality Rate") +
  ggtitle("Quadratic")

hd3 <- 
h3$vars_bins %>%
  filter(!is.nan(rdplot_ci_r) & !is.nan(rdplot_mean_y) & !is.na(rdplot_ci_r) &
           rdplot_N != 1) %>%
  ggplot(aes(x = rdplot_mean_bin, y = rdplot_mean_y)) + 
  geom_point() +
  geom_ribbon(aes(ymin = rdplot_ci_l, ymax = rdplot_ci_r), alpha = .1) + theme_bw() +
  geom_vline(xintercept = 62, linetype = "dashed", color = "darkgrey") +
  geom_line(color= ifelse(h3$vars_poly$rdplot_x <= 62, "red", "blue"),
            aes(x=rdplot_x, y= rdplot_y), data = h3$vars_poly) +
  labs(x = "2014 Index of Medical Score", y = "Mortality Rate") +
  ggtitle("Cubic")

can1 <- 
c1$vars_bins %>%
  filter(!is.nan(rdplot_ci_r) & !is.nan(rdplot_mean_y) & !is.na(rdplot_ci_r) &
           rdplot_N != 1) %>%
  ggplot(aes(x = rdplot_mean_bin, y = rdplot_mean_y)) + 
  geom_point() +
  geom_ribbon(aes(ymin = rdplot_ci_l, ymax = rdplot_ci_r), alpha = .1) + theme_bw() +
  geom_vline(xintercept = 62, linetype = "dashed", color = "darkgrey") +
  geom_line(color= ifelse(c1$vars_poly$rdplot_x <= 62, "red", "blue"),
            aes(x=rdplot_x, y= rdplot_y), data = c1$vars_poly) +
  labs(x = "2014 Index of Medical Score", y = "Mortality Rate") +
  ggtitle("Linear")

can2 <- 
c2$vars_bins %>%
  filter(!is.nan(rdplot_ci_r) & !is.nan(rdplot_mean_y) & !is.na(rdplot_ci_r) &
           rdplot_N != 1) %>%
  ggplot(aes(x = rdplot_mean_bin, y = rdplot_mean_y)) + 
  geom_point() +
  geom_ribbon(aes(ymin = rdplot_ci_l, ymax = rdplot_ci_r), alpha = .1) + theme_bw() +
  geom_vline(xintercept = 62, linetype = "dashed", color = "darkgrey") +
  geom_line(color= ifelse(c2$vars_poly$rdplot_x <= 62, "red", "blue"),
            aes(x=rdplot_x, y= rdplot_y), data = c2$vars_poly) +
  labs(x = "2014 Index of Medical Score", y = "Mortality Rate") +
  ggtitle("Quadratic")

can3 <- 
c3$vars_bins %>%
  filter(!is.nan(rdplot_ci_r) & !is.nan(rdplot_mean_y) & !is.na(rdplot_ci_r) &
           rdplot_N != 1) %>%
  ggplot(aes(x = rdplot_mean_bin, y = rdplot_mean_y)) + 
  geom_point() +
  geom_ribbon(aes(ymin = rdplot_ci_l, ymax = rdplot_ci_r), alpha = .1) + theme_bw() +
  geom_vline(xintercept = 62, linetype = "dashed", color = "darkgrey") +
  geom_line(color= ifelse(c3$vars_poly$rdplot_x <= 62, "red", "blue"),
            aes(x=rdplot_x, y= rdplot_y), data = c3$vars_poly) +
  labs(x = "2014 Index of Medical Score", y = "Mortality Rate") +
  ggtitle("Cubic")

##################################################
ac4 <- 
a4$vars_bins %>%
  filter(!is.nan(rdplot_ci_r) & !is.nan(rdplot_mean_y) & !is.na(rdplot_ci_r) &
           rdplot_N != 1) %>%
  ggplot(aes(x = rdplot_mean_bin, y = rdplot_mean_y)) + 
  geom_point() +
  geom_ribbon(aes(ymin = rdplot_ci_l, ymax = rdplot_ci_r), alpha = .1) + theme_bw() +
  geom_vline(xintercept = 62, linetype = "dashed", color = "darkgrey") +
  geom_line(color= ifelse(a4$vars_poly$rdplot_x <= 62, "red", "blue"),
            aes(x=rdplot_x, y= rdplot_y), data = a4$vars_poly) +
  labs(x = "2014 Index of Medical Score", y = "Mortality Rate") +
  ggtitle("Linear")

ac5 <- 
a5$vars_bins %>%
  filter(!is.nan(rdplot_ci_r) & !is.nan(rdplot_mean_y) & !is.na(rdplot_ci_r) &
           rdplot_N != 1) %>%
  ggplot(aes(x = rdplot_mean_bin, y = rdplot_mean_y)) + 
  geom_point() +
  geom_ribbon(aes(ymin = rdplot_ci_l, ymax = rdplot_ci_r), alpha = .1) + theme_bw() +
  geom_vline(xintercept = 62, linetype = "dashed", color = "darkgrey") +
  geom_line(color= ifelse(a5$vars_poly$rdplot_x <= 62, "red", "blue"),
            aes(x=rdplot_x, y= rdplot_y), data = a5$vars_poly) +
  labs(x = "2014 Index of Medical Score", y = "Mortality Rate") +
  ggtitle("Quadratic")

ac6 <- 
a6$vars_bins %>%
  filter(!is.nan(rdplot_ci_r) & !is.nan(rdplot_mean_y) & !is.na(rdplot_ci_r) &
           rdplot_N != 1) %>%
  ggplot(aes(x = rdplot_mean_bin, y = rdplot_mean_y)) + 
  geom_point() +
  geom_ribbon(aes(ymin = rdplot_ci_l, ymax = rdplot_ci_r), alpha = .1) + theme_bw() +
  geom_vline(xintercept = 62, linetype = "dashed", color = "darkgrey") +
  geom_line(color= ifelse(a6$vars_poly$rdplot_x <= 62, "red", "blue"),
            aes(x=rdplot_x, y= rdplot_y), data = a6$vars_poly) +
  labs(x = "2014 Index of Medical Score", y = "Mortality Rate") +
  ggtitle("Cubic")

hd4 <- 
h4$vars_bins %>%
  filter(!is.nan(rdplot_ci_r) & !is.nan(rdplot_mean_y) & !is.na(rdplot_ci_r) &
           rdplot_N != 1) %>%
  ggplot(aes(x = rdplot_mean_bin, y = rdplot_mean_y)) + 
  geom_point() +
  geom_ribbon(aes(ymin = rdplot_ci_l, ymax = rdplot_ci_r), alpha = .1) + theme_bw() +
  geom_vline(xintercept = 62, linetype = "dashed", color = "darkgrey") +
  geom_line(color= ifelse(h4$vars_poly$rdplot_x <= 62, "red", "blue"),
            aes(x=rdplot_x, y= rdplot_y), data = h4$vars_poly) +
  labs(x = "2014 Index of Medical Score", y = "Mortality Rate") +
  ggtitle("Linear")

hd5 <- 
h5$vars_bins %>%
  filter(!is.nan(rdplot_ci_r) & !is.nan(rdplot_mean_y) & !is.na(rdplot_ci_r) &
           rdplot_N != 1) %>%
  ggplot(aes(x = rdplot_mean_bin, y = rdplot_mean_y)) + 
  geom_point() +
  geom_ribbon(aes(ymin = rdplot_ci_l, ymax = rdplot_ci_r), alpha = .1) + theme_bw() +
  geom_vline(xintercept = 62, linetype = "dashed", color = "darkgrey") +
  geom_line(color= ifelse(h5$vars_poly$rdplot_x <= 62, "red", "blue"),
            aes(x=rdplot_x, y= rdplot_y), data = h5$vars_poly) +
  labs(x = "2014 Index of Medical Score", y = "Mortality Rate") +
  ggtitle("Quadratic")

hd6 <- 
h6$vars_bins %>%
  filter(!is.nan(rdplot_ci_r) & !is.nan(rdplot_mean_y) & !is.na(rdplot_ci_r) &
           rdplot_N != 1) %>%
  ggplot(aes(x = rdplot_mean_bin, y = rdplot_mean_y)) + 
  geom_point() +
  geom_ribbon(aes(ymin = rdplot_ci_l, ymax = rdplot_ci_r), alpha = .1) + theme_bw() +
  geom_vline(xintercept = 62, linetype = "dashed", color = "darkgrey") +
  geom_line(color= ifelse(h6$vars_poly$rdplot_x <= 62, "red", "blue"),
            aes(x=rdplot_x, y= rdplot_y), data = h6$vars_poly) +
  labs(x = "2014 Index of Medical Score", y = "Mortality Rate") +
  ggtitle("Cubic")

can4 <- 
c4$vars_bins %>%
  filter(!is.nan(rdplot_ci_r) & !is.nan(rdplot_mean_y) & !is.na(rdplot_ci_r) &
           rdplot_N != 1) %>%
  ggplot(aes(x = rdplot_mean_bin, y = rdplot_mean_y)) + 
  geom_point() +
  geom_ribbon(aes(ymin = rdplot_ci_l, ymax = rdplot_ci_r), alpha = .1) + theme_bw() +
  geom_vline(xintercept = 62, linetype = "dashed", color = "darkgrey") +
  geom_line(color= ifelse(c4$vars_poly$rdplot_x <= 62, "red", "blue"),
            aes(x=rdplot_x, y= rdplot_y), data = c4$vars_poly) +
  #labs(x = "2014 Index of Medical Score", y = "Mortality Rate") +
  ggtitle("Linear")

can5 <- 
c5$vars_bins %>%
  filter(!is.nan(rdplot_ci_r) & !is.nan(rdplot_mean_y) & !is.na(rdplot_ci_r) &
           rdplot_N != 1) %>%
  ggplot(aes(x = rdplot_mean_bin, y = rdplot_mean_y)) + 
  geom_point() +
  geom_ribbon(aes(ymin = rdplot_ci_l, ymax = rdplot_ci_r), alpha = .1) + theme_bw() +
  geom_vline(xintercept = 62, linetype = "dashed", color = "darkgrey") +
  geom_line(color= ifelse(c5$vars_poly$rdplot_x <= 62, "red", "blue"),
            aes(x=rdplot_x, y= rdplot_y), data = c5$vars_poly) +
  labs(x = "2014 Index of Medical Score", y = "Mortality Rate") +
  ggtitle("Quadratic")

can6 <- 
c6$vars_bins %>%
  filter(!is.nan(rdplot_ci_r) & !is.nan(rdplot_mean_y) & !is.na(rdplot_ci_r) &
           rdplot_N != 1) %>%
  ggplot(aes(x = rdplot_mean_bin, y = rdplot_mean_y)) + 
  geom_point() +
  geom_ribbon(aes(ymin = rdplot_ci_l, ymax = rdplot_ci_r), alpha = .1) + theme_bw() +
  geom_vline(xintercept = 62, linetype = "dashed", color = "darkgrey") +
  geom_line(color= ifelse(c6$vars_poly$rdplot_x <= 62, "red", "blue"),
            aes(x=rdplot_x, y= rdplot_y), data = c6$vars_poly) +
  labs(x = "2014 Index of Medical Score", y = "Mortality Rate") +
  ggtitle("Cubic")

```


```{r, fig.cap="Age-Standardized (Left) and Crude (Right) All Cause Mortality FRDD Fits", fig.height=10, fig.width=8}
(ac1 + ac4)/ (ac2 + ac5) / (ac3 + ac6) + 
  plot_annotation(caption = "Lines represent predicted mortality rate for binned observations, and grey ribbons show 95% confidence intervals")

```

```{r, fig.cap = "Age-Standardized (Left) and Crude (Right) Heart Disease Mortality FRDD Fits", fig.height=10, fig.width=8}
(hd1 + hd4)/ (hd2 + hd5) / (hd3 + hd6)+ 
  plot_annotation(caption = "Lines represent predicted mortality rate for binned observations, and grey ribbons show 95% confidence intervals")
```


```{r,fig.cap = "Age-Standardized (Left) and Crude (Right) Cancer Mortality FRDD Fits", fig.height=10, fig.width=8}
(can1 + can4)/ (can2 + can5) / (can3 + can6)+ 
  plot_annotation(caption = "Lines represent predicted mortality rate for binned observations, and grey ribbons show 95% confidence intervals")
```


### Placebo Tests : Balance on Covariates

```{r}
hhinc <- rdrobust(y = merge.mortb$median_household_income_raw_value_14, 
              x = merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
              c = 62, all=TRUE , masspoints = F, p = 2)
unemp <- rdrobust(y = merge.mortb$unemployment_rate_2014, 
              x = merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
              c = 62, all=TRUE , masspoints = F, p = 2)
hsgrad <- rdrobust(y = merge.mortb$high_school_graduation_raw_value_14, 
              x = merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
              c = 62, all=TRUE , masspoints = F, p = 2)
unins <- rdrobust(y = merge.mortb$uninsured_2014, 
              x = merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
              c = 62, all=TRUE , masspoints = F, p = 2)
obesi <- rdrobust(y = merge.mortb$adult_obesity_2012_2014, 
              x = merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
              c = 62, all=TRUE , masspoints = F, p = 2)
smoke <- rdrobust(y = merge.mortb$adult_smoking_value, 
              x = merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
              c = 62, all=TRUE , masspoints = F, p = 2)
inact <- rdrobust(y = merge.mortb$physical_inactivity_2012_2014, 
              x = merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
              c = 62, all=TRUE , masspoints = F, p = 2)
white <- rdrobust(y = merge.mortb$percent_non_hispanic_white_raw_value_14, 
              x = merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
              c = 62, all=TRUE , masspoints = F, p = 2)
black <- rdrobust(y = merge.mortb$percent_non_hispanic_african_american_raw_value_14, 
              x = merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
              c = 62, all=TRUE , masspoints = F, p = 2)
hisp <- rdrobust(y = merge.mortb$percent_hispanic_raw_value_14, 
              x = merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
              c = 62, all=TRUE , masspoints = F, p = 2)
rura <- rdrobust(y = merge.mortb$percent_rural_raw_value_14, 
              x = merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
              c = 62, all=TRUE , masspoints = F, p = 2)
nine <- rdrobust(y = merge.mortb$age_adjusted_rate_1999a, 
              x = merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
              c = 62, all=TRUE , masspoints = F, p = 2)
five <- rdrobust(y = merge.mortb$age_adjusted_rate_2009a, 
              x = merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
              c = 62, all=TRUE , masspoints = F, p = 2)
four <- rdrobust(y = merge.mortb$age_adjusted_rate_2004a, 
              x = merge.mortb$newimu14, fuzzy = merge.mortb$treatment,
              c = 62, all=TRUE , masspoints = F, p = 2)

#create a nice table of results
outcome <- c("Median HH Income", "Unemployment", "High School Graduation",
             "Uninsured", "Adult Obesity", "Smoking", "Physical Inactivity",
             "Percent White", "Percent Black", "Percent Hispanic", "Percent Rural",
             "1999 All Cause Mortality", "2004 All Cause Mortality", "2009 All Cause Mortality")

tau.rdd <- c(hhinc$Estimate[2], unemp$Estimate[2], hsgrad$Estimate[2],
             unins$Estimate[2], obesi$Estimate[2], smoke$Estimate[2],
             inact$Estimate[2], white$Estimate[2], black$Estimate[2],
             hisp$Estimate[2], rura$Estimate[2], nine$Estimate[2], four$Estimate[2],
             five$Estimate[2])

ci.robu <- c(paste0(round(hhinc$ci[3,1],2), " - ", round(hhinc$ci[3,2],2)),
             paste0(round(unemp$ci[3,1],2), " - ", round(unemp$ci[3,2],2)),
             paste0(round(hsgrad$ci[3,1],2), " - ", round(hsgrad$ci[3,2],2)),
             paste0(round(unins$ci[3,1],2), " - ", round(unins$ci[3,2],2)),
             paste0(round(obesi$ci[3,1],2), " - ", round(obesi$ci[3,2],2)),
             paste0(round(smoke$ci[3,1],2), " - ", round(smoke$ci[3,2],2)),
             paste0(round(inact$ci[3,1],2), " - ", round(inact$ci[3,2],2)),
             paste0(round(white$ci[3,1],2), " - ", round(white$ci[3,2],2)),
             paste0(round(black$ci[3,1],2), " - ", round(black$ci[3,2],2)),
             paste0(round(hisp$ci[3,1],2), " - ", round(hisp$ci[3,2],2)),
             paste0(round(rura$ci[3,1],2), " - ", round(rura$ci[3,2],2)),
             paste0(round(nine$ci[3,1],2), " - ", round(nine$ci[3,2],2)),
             paste0(round(four$ci[3,1],2), " - ", round(four$ci[3,2],2)),
             paste0(round(five$ci[3,1],2), " - ", round(five$ci[3,2],2))
             )

#bind together for table
res.tab <- cbind.data.frame(outcome, tau.rdd, ci.robu)
res.tab$tau.rdd <- round(res.tab$tau.rdd, 2)

names(res.tab) <- c("Outcome", "Estimate", "Robust")

res.tab %>%
#specify which ones should be bold
  mutate(
     Robust = cell_spec(Robust, bold = ifelse(substr(Robust,1,1)!= "-", T, F))) %>%
  kable("latex", booktabs = T, escape = F, align= c('l', 'r', 'r', 'r', 'r', 'r'),
        caption = "Placebo Effects of NHSC Participation") %>%
  kable_styling(row_label_position = "l",) %>%
  footnote(general = "Estimates represent tau FRD using a local regression with a triangular kernel")%>%
  add_footnote(label = "Bold face denotes statistical significance (p < 0.05)") %>%
  add_footnote(label = "All Cause Mortality is Age-Standardized")

```


```{r, include=FALSE, eval=FALSE}
#run rdds with outcomes that I wouldn't expect to be associated
#sensitivity analyses: using 1999 mortality as an outcome
make_rdd_plot_data <- function(outcome, cut = merge.mortb$newimu14, covars = NULL){
  ik.bw <- IKbandwidth(Y = outcome,
                       X = cut, cutpoint = 62)

  tempframe <- cbind.data.frame(c(1:24, ik.bw),
                                rep(0,25),
                                rep(0,25),
                                rep(0,25),
                                rep(0,25),
                                rep(0,25),
                                rep(0,25),
                                rep(0,25))

  names(tempframe) <- c("bw", "estimate_bc", "estimate_us", "upper_bc","lower_bc",
                         "upper_rob","lower_rob",
                         "nObs")

  for (i in 1:nrow(tempframe)){
    j <- tempframe[i,1]
      rd <- rdrobust(y = outcome, 
                x = cut, fuzzy = merge.mortb$treatment, h = j,
                c = 62, all=TRUE , masspoints = F, p = 2)
     tempframe[i,] <- c(j,
                       rd$Estimate[2],
                       rd$Estimate[2],
                       rd$ci[2,2], rd$ci[2,1],
                       rd$ci[3,2], rd$ci[3,1],
                       sum(rd$N_h))
  }
  
  
  return(tempframe)  
}

plot_rdd_data <- function(dat){
  int <- dat[25,1] #ik bw
  ymin <- min(dat$lower_rob)
  ymax <- max(dat$upper_rob)
  dat %>%
    ggplot(aes(x = bw, y = estimate_bc)) + geom_point(color = "black") +
    geom_ribbon(aes(ymin = lower_rob, ymax = upper_rob), alpha =.3, fill = "#00BFC4") +
    geom_point(aes(x = bw, y = estimate_us), color = "#F8766D") + 
    geom_ribbon(aes(ymin = lower_bc, ymax = upper_bc), alpha =.3, fill = "#F8766D") +
    theme_bw() + labs(x = "Absolute Distance From Cutoff", y = "LATE")+
    geom_text(aes(label = paste(nObs)), nudge_y = .16,
              check_overlap = TRUE, angle = 60)+
    geom_vline(xintercept = int, linetype = "dashed", color = "darkgrey")+
    geom_hline(yintercept = 0, color = "black")+
    theme(panel.grid.minor.x = element_blank()) #+
   # ylim(c(ymin + 50 , ymax - 50))

}


plot_rdd_data3 <- function(dat){
  int <- dat[25,1] #ik bw
  ymin <- min(dat$lower_rob)
  ymax <- max(dat$upper_rob)
  dat %>%
    ggplot(aes(x = bw, y = estimate_bc)) + geom_point(color = "black") +
    geom_ribbon(aes(ymin = lower_rob, ymax = upper_rob), alpha =.3, fill = "#00BFC4") +
    geom_point(aes(x = bw, y = estimate_us), color = "#F8766D") + 
    geom_ribbon(aes(ymin = lower_bc, ymax = upper_bc), alpha =.3, fill = "#F8766D") +
    theme_bw() + labs(x = "Absolute Distance From Cutoff", y = "LATE")+
    geom_text(aes(label = paste(nObs)), nudge_y = .6,
              check_overlap = TRUE, angle = 60)+
    geom_vline(xintercept = int, linetype = "dashed", color = "darkgrey")+
    geom_hline(yintercept = 0, color = "black")+
    theme(panel.grid.minor.x = element_blank()) #+
   # ylim(c(ymin + 50 , ymax - 50))

}

plot_rdd_data2 <- function(dat){
  int <- dat[25,1] #ik bw
  ymin <- min(dat$lower_rob)
  ymax <- max(dat$upper_rob)
  dat %>%
    ggplot(aes(x = bw, y = estimate_bc)) + geom_point(color = "black") +
    geom_ribbon(aes(ymin = lower_rob, ymax = upper_rob), alpha =.3, fill = "#00BFC4") +
    geom_point(aes(x = bw, y = estimate_us), color = "#F8766D") + 
    geom_ribbon(aes(ymin = lower_bc, ymax = upper_bc), alpha =.3, fill = "#F8766D") +
    theme_bw() + labs(x = "Absolute Distance From Cutoff", y = "LATE")+
    geom_text(aes(label = paste(nObs)), nudge_y = 10000,
              check_overlap = TRUE, angle = 60)+
    geom_vline(xintercept = int, linetype = "dashed", color = "darkgrey")+
    geom_hline(yintercept = 0, color = "black")+
    theme(panel.grid.minor.x = element_blank()) #+
   # ylim(c(ymin + 50 , ymax - 50))

}
```


```{r, fig.width = 8, fig.height = 10, fig.cap = 'Fuzzy RDD Estimated Effects on: A = 2014 High School Graduation Rate, B = 2014 Unemployment Rate, C = 2014 Median Household Income. As for the outcomes of interest, LATEs are estimated with as local regressions with a triangular kernel and a second order polynomial. Dashed line shows IK bandwidth, blue bands show robust 95% CI and dark bands show standard 95% CI.', include = FALSE, eval = FALSE}

plac1 <-
make_rdd_plot_data(outcome = merge.mortb$high_school_graduation_raw_value_14) %>%
  plot_rdd_data3()

plac2 <- 
make_rdd_plot_data(outcome = merge.mortb$unemployment_rate_2014) %>%
  plot_rdd_data()

plac3 <- 
make_rdd_plot_data(outcome = merge.mortb$median_household_income_raw_value_14) %>%
  plot_rdd_data2()

plac1 / plac2 / plac3 + plot_annotation(tag_levels = "A")


```


```{r,fig.width = 8, fig.height = 10, fig.cap = 'Fuzzy RDD Estimated Effects on: A = 2014 Adult Cigarette Smoking Rate, B = 2014 Adult Obesity Rate, C = 2014 Uninsured Rate. LATEs are estimated with as local regressions with a triangular kernel and a second order polynomial. Dashed line shows IK bandwidth, blue bands show robust 95% CI and dark bands show standard 95% CI.',include=FALSE, eval = FALSE}


plac4 <- 
make_rdd_plot_data(outcome = merge.mortb$adult_smoking_value) %>%
  plot_rdd_data()

plac5 <- 
make_rdd_plot_data(outcome = merge.mortb$adult_obesity_2012_2014) %>%
  plot_rdd_data()

plac6 <- 
make_rdd_plot_data(outcome = merge.mortb$uninsured_2014) %>%
  plot_rdd_data()


plac4 / plac5 / plac6 + plot_annotation(tag_levels = "A")

```

### Placebo Tests: Using Alternate Cutoffs

```{r}
make_rdd_plot_data_placebo <- function(outcome, cut = merge.mortb$newimu14, cutoff){
  ik.bw <- IKbandwidth(Y = outcome,
                       X = cut, cutpoint = cutoff)

  tempframe <- cbind.data.frame(c(ik.bw),
                                rep(0,1),
                                rep(0,1),
                                rep(0,1),
                                rep(0,1),
                                rep(0,1),
                                rep(0,1),
                                rep(0,1))

  names(tempframe) <- c("bw", "estimate_bc", "estimate_us", "upper_bc","lower_bc",
                         "upper_rob","lower_rob",
                         "nObs")

  for (i in 1:nrow(tempframe)){
    j <- tempframe[i,1]
      rd <- rdrobust(y = outcome, 
                x = cut, fuzzy = merge.mortb$treatment, h = ik.bw,
                c = cutoff, all=TRUE , masspoints = F, p = 2)
     tempframe[i,] <- c(j,
                       rd$Estimate[2],
                       rd$Estimate[2],
                       rd$ci[2,2], rd$ci[2,1],
                       rd$ci[3,2], rd$ci[3,1],
                       sum(rd$N_h))
  }
  
  
  return(tempframe)  
}

plac.cut <- 
purrr::map_df(.x = seq(40, 90, 1), 
               .f = ~make_rdd_plot_data_placebo(outcome = merge.mortb$age_adjusted_rate_2015a,
                                               cutoff = .x))
plac.cut$cutoff <- 40:90

plot_rdd_data <- function(dat){
  int <- dat[25,1] #ik bw
  dat <- dat %>% filter(bw >= 2)
  ymin <- min(dat$lower_rob)
  ymax <- max(dat$upper_rob)
  dat %>%
    ggplot(aes(x = bw, y = estimate_bc)) + geom_point(color = "black") +
    geom_ribbon(aes(ymin = lower_rob, ymax = upper_rob), alpha =.3, fill = "#00BFC4") +
    geom_point(aes(x = bw, y = estimate_us), color = "#F8766D") + 
    geom_ribbon(aes(ymin = lower_bc, ymax = upper_bc), alpha =.3, fill = "#F8766D") +
    theme_bw() + labs(x = "Absolute Distance From Cutoff", y = "LATE")+
    geom_text(aes(label = paste(nObs)), nudge_y = 250, nudge_x = -.2,
              check_overlap = TRUE, angle = 60)+
    geom_vline(xintercept = int, linetype = "dashed", color = "darkgrey")+
    geom_hline(yintercept = 0, color = "black")+
    xlim(c(2,23))+ theme(panel.grid.minor.x = element_blank()) +
    ylim(c(ymin + 50 , ymax - 50))

}



```



